title: Just a Game Blog
author: Dave Taylor
email: dptaylo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I like games. Collecting games, playing games, and tinkering with rules. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
